[serveurs]
serveur02 ansible_host=192.168.196.150
serveur03 ansible_host=192.168.196.151

[serveurs:vars]
ansible_user=osboxes
ansible_password=osboxes
ansible_become_password=osboxes
ansible_become_method=sudo
# On force Ansible à utiliser une méthode de communication plus simple
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_extra_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no'